### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by badboycxcc** [bytemate/chatapi#11]
<img width="1223" alt="截屏2023-02-01 下午5 51 03" src="https://user-images.githubusercontent.com/72059221/216009781-20fde930-786a-4d94-bb8d-6c17f6d88d9f.png">

**Comment by fuergaosi233** [comment]
Please provide Curl cmd 🤔

**Comment by badboycxcc** [comment]
原因在于代码中 userId I 大写了
