### ISSUE TITLE
Error of prisma.chatGPTAccount.deleteMany() on npm run seed 

### ISSUE THREAD

**Issue by jcevo** [bytemate/chatapi#16]
error like this 
![image](https://user-images.githubusercontent.com/4157773/216772254-b6d1fd56-83c2-4f17-afbc-da2c5b349883.png)

already set CAPTCHA_TOKEN to .env
![image](https://user-images.githubusercontent.com/4157773/216772395-ca427135-2bc1-4918-884b-e2d169598489.png)

account like this
![image](https://user-images.githubusercontent.com/4157773/216772603-38ce2a8c-e853-4f42-afc6-d399a22f7d3a.png)

**Comment by craw11** [comment]
有人解决了吗

**Comment by GingerNg** [comment]
npx prisma migrate dev --name init  before npm run seed
